### ISSUE TITLE
browse-js -- btns not being stripped

### ISSUE THREAD

**Issue by dcnb** [uidaholib/collectionbuilder-cdm-template#73]
I found this out working on barstock branch. the buttons would put out links that ended "# basketball" and then searched for " basketball" 

I fixed this in the branch by adding a trim to the btn for loop here: 

 for (var i = 0, len = btns.length; i < len; i++) {
      if(btns[i] != "") {
        card += '<a class="btn btn-sm btn-secondary m-1 text-wrap" href="{{ '/browse.html' | relative_url }}#' + encodeURIComponent(btns[i].trim()) + '">' + btns[i].trim() + '</a>';
      }

but I'll let @evanwill decide if that works

**Comment by evanwill** [comment]
good catch. I added the `.trim()`. The spaces were there in our demo collection too, but it didn't seem to break anything because it was consistently there. Stuff that comes through `array_count_uniq` gets stripped, so subjects cloud etc doesn't have the spaces already.
I added `.trim()` to the browse query too, so you can put in extra spaces and not break.
